<?php

namespace AppBundle\Repository;

/**
 * BigCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BigCityRepository extends \Doctrine\ORM\EntityRepository
{
}
